apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-configmap
  namespace: muchtodo
data:
  PORT: "8080"
  MONGO_URI: "mongodb://root:example@mongodb-service:27017/much_todo_db?authSource=admin"
  DB_NAME: "much_todo_db"
  JWT_EXPIRATION_HOURS: "72"
  LOG_LEVEL: "DEBUG"
  LOG_FORMAT: "json"
  ENABLE_CACHE: "true"
  REDIS_ADDR: "redis:6379"
  REDIS_PASSWORD: ""
